export enum PathAPI {
  Root = '/',
  Profile = '/profile',
  Dialogs = '/dialogs',
  Users = '/users',
  Settings = '/settings',
  Security = '/security',
  Captcha = '/get-captcha-url',
  Auth = '/auth',
  Me = '/me',
  Login = '/login',
  Photo = '/photo',
  Status = '/status',
  Follow = '/follow',
  Page = 'page',
  Count = 'count',
  Friend = 'friend',
  Term = 'term',
  Qotd = 'qotd'
}
